storage: /verdaccio/storage
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  pypestream-npmjs:
    url: https://registry.npmjs.org/
    auth:
      type: bearer
      token_env: true # by defaults points to the environment variable `NPM_TOKEN`
  npmjs:
    url: https://registry.npmjs.org/
notify:
  method: POST
  headers: [{ "Content-Type": "application/json" }]
  endpoint: https://deno-as-webhook.onrender.com
  content:
    '{"message":"New package published: * {{ name }}*","notify":true,"message_format":"text", "version": "{{#each versions}} v{{version}}{{/each}}", "schema": {
    {{#each versions}}
    {{#each this.schema}}
    "{{@key}}": "{{this}}"
    {{/each}}
    {{/each}}
    }'
packages:
  "@pypestream/test-pkg":
    access: $all
    publish: $authenticated
    proxy: pypestream-npmjs
  "@pypestream/email-templates":
    access: $allg
    publish: $authenticated
    proxy: pypestream-npmjs
  "**":
    proxy: npmjs
    access: $all
    publish: $all
log: { type: stdout, format: pretty, level: http }
