FROM ghcr.io/esm-dev/esm.sh
ADD ./config.json /etc/esmd/config.json
ENV NPM_REGISTRY=$VERDACCIO_HOST
# CMD ["esmd", "esmd --config", "/etc/esmd/config.json", ""]

CMD ["sh", "-c", "esmd --config /etc/esmd/config.json --env ${NPM_REGISTRY}"]
