version: "3.1"

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: "verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./.verdaccio:/verdaccio/conf"
  esm.sh:
    image: ghcr.io/esm-dev/esm.sh
    container_name: "esm.sh"
    networks:
      - node-network
    environment:
      - NPM_REGISTRY=http://verdaccio:4873/
    ports:
      - "8080:8080"
networks:
  node-network:
    driver: bridge
