services:
  - type: web
    name: verdaccio
    region: oregon # optional (defaults to oregon)
    plan: starter # optional (defaults to starter)
    env: docker
    disk:
      name: verdaccio-data
      mountPath: /verdaccio/storage
      sizeGB: 1 # optional

  - type: web
    name: esm
    env: docker
    dockerfilePath: ./Dockerfile.esm
    envVars:
      - key: NPM_REGISTRY
        fromService:
          name: verdaccio
          type: web
          property: host
