# previewsEnabled: true

services:
  - type: web
    name: pypestream-registry
    region: oregon # optional (defaults to oregon)
    plan: starter # optional (defaults to starter)
    env: docker
    disk:
      name: verdaccio-data
      mountPath: /verdaccio/storage
      sizeGB: 1 # optional

  - type: web
    name: pypestream-registry-esm
    env: docker
    dockerfilePath: ./Dockerfile.esm
    envVars:
      - key: NPM_REGISTRY
        fromService:
          name: pypestream-registry
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: NEW_API
        value: test
