services:
  - type: web
    name: verdaccio
    region: oregon # optional (defaults to oregon)
    plan: starter # optional (defaults to starter)
    env: docker

  - type: web
    name: esm
    runtime: image
      image:
        url: docker.io/my-name/my-image:latest
          envVars:
            - key: NPM_REGISTRY
              fromService:
                name: verdaccio
                type: web
                property: host
