services:
  - type: web
    name: verdaccio
    region: oregon # optional (defaults to oregon)
    plan: starter # optional (defaults to starter)
    env: docker
    disk:
      name: verdaccio-data
      mountPath: ./verdaccio/conf/storage
      sizeGB: 1 # optional
