services:
  - type: web
    name: verdaccio
    region: oregon # optional (defaults to oregon)
    plan: starter # optional (defaults to starter)
    env: docker

  - type: web
    name: esm
    runtime: image
    image:
      url: ghcr.io/esm-dev/esm.sh:v135
    envVars:
      - key: NPM_REGISTRY
        fromService:
          name: verdaccio
          type: web
          property: host
